### ISSUE TITLE
README/log improvements: list names of supported devices ("description"), quirks, ...

### ISSUE THREAD

**Issue by MichaelAnders** [rofafor/vdr-plugin-satip#74]
If SATIP automatically finds the SATIP hardware via Upnp then user gets this:
SATIP: Adding server 'a.b.x.y|DVBS2-2|OctopusNet' Bind: default Filters: none CI: yes Quirks: CiXpmt

However, there is a problem with this part:
"The plugin accepts also a "--server" (-s) command-line parameter, that can be used to manually configure static SAT>IP servers if autodetection via UPnP somehow can't be used..." ... "<ipaddress>|<model>|<description>"

The word "description" indicates "any name you like". It does not tell the user that a <device name> from a specific list (in server.c) needs to be used. Just by accident I searched the repo for OctopusNet and then found what this actually does in server.c...

As a result, using a "description" of "DD" (which I initially used) results in:
SATIP: Adding server 'a.b.x.y|DVBS2-2|DD' Bind: default Filters: none CI: no Quirks: none

On the other hand, using "description" of "OctopusNet" results in:
SATIP: Adding server 'a.b.x.y|DVBS2-2|OctopusNet' Bind: default Filters: none CI: yes Quirks: CiXpmt

And is "model" the right name to specify the type of "tuner" used by the SATIP hardware? Model sounds more like an actual SATIP hardware "model"?

Improvement suggestions:

1. Change the word "description" to "device name"
2. Change the word "model" to "tuner"
2. List the possible "device names" as specified in server.c in the README and also output them in the vdr help output
3. List the possible "quirks" that can be specified / are used for each device name (could help users with similar hardware which is just not (yet) supported by satip plugin)
3. Add info in the log about the device being used: "SATIP: Adding server 'a.b.x.y|DVBS2-2|...' Device: OctopusNet/.../unknown Bind: ... Filters: .../unknown CI: .../unknown Quirks: .../unknown"

**Comment by rofafor** [comment]
What's your reason not using the auto-detection? The command-line interface was implemented for rare networking setups where broadcast messages couldn't be used.

1. Description is actually "friendlyName", that's shortened version of "modelDescription" field. In that sense, it's more a description rather than name. 
2. Model is actually "capabilities" and it just gives a hint e.g. what kind of tuners are available. I agree the "modulation system" would have be better.
3. Nope - this plugin is made for auto-detection. If you're bypassing it, you'll need to know what you're doing. Maintaining a device database is something I really want to avoid.
4. The quirks are my mistake that never should have implemented (non-standard features and buggy firmwares). If you need them, you, you certainly can read the available ones from server.h.
5. I don't get this one as it's already there. Are you looking for a notification, if the used server is a broken/non-standard one and quirks are disabled?

**Comment by rofafor** [comment]
I've improved the documentation in https://github.com/rofafor/vdr-plugin-satip/commit/02296fa8d7aec88dbfaafa01d64798c6d2a09e18. Hopefully it's enough.
