### ISSUE TITLE
Returncode 404 from minisatip is not handled

### ISSUE THREAD

**Issue by jojo61** [rofafor/vdr-plugin-satip#77]
I fixed an issue with minisatip and tuner sharing with one LNB.   Now minsatip returns correctly the code 404 when I try to tune to a transponder on the slave tuner that can not be handled because the master tuner is busy on another band.

As 404 is not handled this results in a frozen screen. It would be better if the plugin could indicate to the vdr that the channel is not available when 404 is received. That way vdr would print a message "channel unavailable" and not tune to the new channel.

**Comment by rofafor** [comment]
IIRC, this would required tuning code operating in a blocking mode making VDR much less responsive.

**Comment by jojo61** [comment]
Well, a frozen screen is not much responsive ether :-)
Is there any other solution possible ? The vdr itself does check if a transponder is tunable befor switching to it. But with satip it seems more difficult.  
Also satip does not honor shared LNBs and vdr checks it only for build in tuners. I agree the the satip server should do it, but if you do not wait for the tuning answer maybe satip could do it before trying to tune.

**Comment by jojo61** [comment]
After further investigating the issue I come to the conclusion that the plugin should handle bonded devices. This is missing in device.c and it is available in the vdr device handling.  That way all the handling of non tunable return codes would be obsolete.

**Comment by rofafor** [comment]
The frozen picture is nothing when you're zapping with channel up and every zap takes seconds before proceeding the next channel with an outdated channels.conf. :)

Anyway, bonded devices were introduced later than this plugin and documentation states: `May be dropped in a future version, if a better solution is found. Do not use otherwise!`. The plugin has been developed for DVB-T/C only and all the satellite stuff just happens to work somehow at some level. I never had any satellite hardware to test it and I don't even have any working VDR setup right now. Contributions are more than welcome!

IMO, retrying is better than any exit strategy because we're talking about network devices having networking issues here.

**Comment by jojo61** [comment]
As I need bonding for my satellite installation I will eventually do it myself. I will send you a diff if ready.
It will take some time as I will go on vacation soon :-)

**Comment by jojo61** [comment]
I switched to unicable and do not need bonding anymore :-)
